<?php
namespace app\components\widgets;

use yii\base\Widget;
use yii\helpers\Html;

class SidebarWidget extends Widget
{

    public $categoryItems;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        return $this->render('sidebar',['categoryItems'=>$this->categoryItems]);
    }


}