<?php


namespace app\components\widgets;


use yii\base\Widget;

class VideoDetailWidgets extends Widget
{
  public $videoItem;



    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        return $this->render('video_detail',['videoItem'=>$this->videoItem]);
    }


}